### ISSUE TITLE
About Sequence from UM Ford Center for Autonomous Vehicles.

### ISSUE THREAD

**Issue by wyz-coding** [specarmi/Thermal_SuperPoint_SLAM#3]
Hello, author:  
 
I am trying to test your algorithm, but I have encountered some problems temporarily. 

I noticed in your video that the sequence you used in the test came from UM Ford Center for Autonomous Vehicles.  
 
But I did not find the relevant sequence in  UM Ford Center for Autonomous Vehicles. 

If possible, could you please provide the download link of the relevant image sequence or other relevant links?  
 
Best wishes.

![Thermal SuperPoint SLAM 00-04-50 20210910-231047359](https://user-images.githubusercontent.com/65948863/132876076-aa9bb988-b3db-41e4-a8fe-f654d3efdd6c.jpg)

**Comment by specarmi** [comment]
Hi, I am happy to see your interest but unfortunately I cannot provide the data. FCAV is my lab and that sequence has not been published.

**Comment by wyz-coding** [comment]
> Hi, I am happy to see your interest but unfortunately I cannot provide the data. FCAV is my lab and that sequence has not been published.

Hi:

thank you for your reply.

Looking forward to reading your new work and new publications.
